site_name: OBO Semantic Engineering Training
theme: material
markdown_extensions:
  - toc:
      permalink: true
nav:
  - About the course: index.md
  - Getting started with learning: getting_started.md
  - Overview of lessons and tutorials: overview.md
  - Contribute to the course: contributing.md
  - Courses:
      - ICBO 2021 Tutorial: tutorial/icbo2021.md
      - Monarch Ontology Training: courses/monarch-obo-training.md
  - Lessons:
      - Contributing to OBO ontologies: lesson/contributing_to_obo_ontologies.md
      - Ontology Pipelines with ROBOT: lesson/ontology_pipelines.md
      - Analysing Linked Data: lesson/analysing_linked_data.md
      - Application Ontology Development: lesson/application_ontology_development.md
      - Automating Ontology Workflows: lesson/automating_ontology_workflows.md
      - Developing an OBO Ontology: lesson/developing_an_obo_ontology.md
      - Developing an Application Ontology: lesson/developing_application_ontologies.md
      - Ontology Design: lesson/ontology_design.md
      - Ontology Development: lesson/ontology_development.md
      - Ontology Fundamentals: lesson/ontology_fundamentals.md
      - Ontology term use: lesson/ontology_term_use.md
      - RDF: lesson/rdf.md
      - Semantic Database Fundamentals: lesson/semantic_database_fundamentals.md
      - Disease and Phenotype Ontologies: lesson/using_disease_and_phenotype_ontologies.md
  - Tutorials:
      - ROBOT Mini-Tutorial 1 - Convert, Extract and Template: tutorial/robot_tutorial_1.md
      - ROBOT Mini-Tutorial 2 - Annotate, Merge, Reason and Diff: tutorial/robot_tutorial_2.md
      - ROBOT Mini-Tutorial QC - Quality Control with report and query: tutorial/robot_tutorial_qc.md
      - GitHub Fundamentals for OBO Engineers: tutorial/github_fundamentals.md
      - GitHub Issue for OBO Engineers: tutorial/github_issues.md
      - Linked Data Tutorial: tutorial/linking-data.md
      - ODK - Managing imports: tutorial/managing-dynamic-imports-odk.md
      - ODK - Managing ontology releases: tutorial/managing-ontology-releases-odk.md
      - ODK - Migrating to ODK: tutorial/migrating-ontology-to-odk.md
  - How-to guides:
      - Installing ELK in Protege: howto/installing_elk_in_protege.md
      - Setting up the ODK: howto/odk_setup.md
      - Clone the Mondo ontology repository: howto/clone_mondo_repo.md
      - Creating an GitHub Fork: howto/github_create_fork.md
      - Creating an GitHub Pull Request: howto/github_create_pull_request.md
      - Browsing and Searching Mondo: howto/protege_browse_search.md
  - Reference:
      - GitHub Desktop: reference/github_desktop.md
      - Semantic Engineering Toolbox: reference/semantic_engineering_toolbox.md
      - Tables and Triples: reference/tables-and-triples.md
      - Reasoning: reference/reasoning.md
      - A day in the life of an ontology curator: reference/ontology-curator.md
  - OBOOK Editors:
      - How to add images: images/index.md
      - New lesson template: config/template.md
      - Case studies for teaching: teaching/case_studies.md


